apiVersion: skaffold/v4beta7
kind: Config

manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml

build:
  artifacts:
    - image: asia-south1-docker.pkg.dev/testing-puneeth/testing-cicd/portfolio

deploy:
  kubectl: {}