apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline

metadata:
  name: portfolio-pipeline

description: Portfolio CI/CD Pipeline

serialPipeline:
  stages:
    - targetId: production
      profiles: []